receivers:
  receiver/OTLP/springBootActuator/GRPC:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  receiver/OTLP/springBootActuator/HTTP:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
#  receiver/prometheus/externalAppScrape:
#    config:
#      scrape_configs:
#        - job_name: 'external-app-prometheus-scrape'
#          scrape_interval: 3s
#          static_configs:
#            - targets: ['host.docker.internal:8080']
  receiver/prometheus/otelContribScrape:
    config:
      scrape_configs:
        - job_name: 'otel-self-prometheus-scrape'
          scrape_interval: 3s
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:
    timeout: 5s
    send_batch_size: 50
    send_batch_max_size: 500

exporters:
  exporter/debug:
    verbosity: basic
#    verbosity: detailed
#  exporter/grafanaLGTM/lokiProprietary:
#    endpoint: "http://host.docker.internal:3100/loki/api/v1/push" # If running in testcontainer, programmatically substitute with mapped port
#    tls:
#      insecure: true
#  exporter/grafanaLGTM/GRPC:
#    endpoint: "http://host.docker.internal:4317" # If running in testcontainer, programmatically substitute with mapped port
#    tls:
#      insecure: true
  exporter/grafanaLGTM/HTTP:
    endpoint: "http://host.docker.internal:4318" # If running in testcontainer, programmatically substitute with mapped port
    tls:
      insecure: true
#  exporter/grafanaLGTM/prometheusProprietary/Push:
#    endpoint: "http://host.docker.internal:9009/api/v1/otlp/v1/metrics" # If running in testcontainer, programmatically substitute with mapped port
#    tls:
#      insecure: true

extensions:
  health_check: {}
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

service:
  pipelines:
    logs:
      receivers: [receiver/OTLP/springBootActuator/GRPC, receiver/OTLP/springBootActuator/HTTP]
      processors: [batch]
      exporters: [exporter/debug, exporter/grafanaLGTM/HTTP]
    traces:
      receivers: [receiver/OTLP/springBootActuator/GRPC, receiver/OTLP/springBootActuator/HTTP]
      processors: [batch]
      exporters: [exporter/debug, exporter/grafanaLGTM/HTTP]
    metrics:
      receivers: [receiver/OTLP/springBootActuator/GRPC, receiver/OTLP/springBootActuator/HTTP, receiver/prometheus/otelContribScrape]
      processors: [batch]
      exporters: [exporter/debug, exporter/grafanaLGTM/HTTP]
  extensions: [health_check, pprof, zpages]
